CREATE DATABASE AMAZON_CLONE
USE AMAZON_CLONE
CREATE TABLE USER_ACCOUNTS(ID INT,
NAME VARCHAR(20),
EMAIL_ID VARCHAR(30),
MOBILE_NO BIGINT);
CREATE TABLE PRIME_ACCOUNTS(ID INT,NAME VARCHAR(20),EMAIL_ID VARCHAR(30),MOBILE_NO BIGINT);
CREATE TABLE PRODUCTS(PRODUCT_ID INT,PRODUCT_NAME VARCHAR(50),PRODUCT_PRICE INT,DISCOUNT_PRICE INT);
CREATE TABLE ORDERS(ID INT,PRODUCT_NAME VARCHAR(50),FINAL_PRICE INT,ADDRESS VARCHAR(100))
DESC USER_ACCOUNTS;
SHOW TABLES